### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by weberc2** [weberc2/builder#18]
Clean up the code before the public announcement so the code is clean and attractive to potential collaborators. This implies an audit pass, but off the top of my head:

- [x] BuilderArgs can be removed
- [ ] Clean up "plugins"
    - [x] Probably no need for `plugins/plugins.go`
    - [x] Remove the boilerplate required to create a plugin in the common case. Consider removing the notion of a "Factory" altogether. It hasn't been useful so far.
    - [ ] Is it a plugin if it's compiled in? Should we pick a different term instead of "plugin"?
    - [ ] Does a plugin include the macros that reference it? Should these macros be external files (related to #7)?
    - [ ] #23 (Easy marshalling to/from `input` types); this should clean up the individual plugin code by removing the repetitive parsing and validation of inputs
    - [ ] #25 (Standardize subprocess calls); this should also clean up the individual plugins' code by removing the repetitive management of subprocess calls and temporary directory management
